### PR TITLE
Add missing code for hardforks 20-21 #1455 #1468

### LINKED ISSUE #1468: STEEMIT_NUM_HARDFORKS needs to be bumped
#1455 was not complete, `STEEMIT_NUM_HARDFORKS` also needs updated

### PR DESCRIPTION
**Pull request by theoreticalbts**
This PR completes incomplete code in #1455.  The relevant issue is #1468

### CODE REVIEW

**Comment by mvandeberg** [comment]
I purposefully left this out. Now, the blockchain version will be reported as 0.21.0 by anyone running this branch and we do not want that. Witnesses running this branch will vote for hardforks that have not been defined yet. CI passes without this. If we needed this boilerplate for testing, we should decouple HF version with the constraint that blockchain_version <= hardfork_version. And witnesses will only vote for hardfork times that are <= to their blockchain_version.

**Comment by theoreticalbts** [comment]
Rebased, let's hold off on merging this until I can check it with my new test in PR #1467

**Comment by theoreticalbts** [comment]
Oops, made a mistake in that push, reverting.

**Comment by theoreticalbts** [comment]
Everything looks OK.

**Pull request merged**
