### PR TITLE
update min boost version in doc/building.md

### PR DESCRIPTION
**Pull request by roadscape**
#1030

### CODE REVIEW

**Comment by Gandalf-the-Grey** [comment]
That's not a small change because Ubuntu 16.04 LTS has packaged boost 1.58
On Debian Stable which has boost 1.55 packaged, people need to build some boost ( 1.58 <= x <= 1.60) anyway
But for Ubuntu 16.04 LTS (AFAICT most common distro/version among witnesses) it is:
to build boost or not to build

**Comment by mvandeberg** [comment]
Our docker images are Ubuntu 16.04 LTS afaik. Maybe I am mistaken and they are using Boost 1.58 (I thought they were using 1.60). Which then begs the question, why did roadscape's build fail with 1.58?

**Comment by roadscape** [comment]
My build on Ubuntu 14.04 failed with 1.58

**Comment by Gandalf-the-Grey** [comment]
so probably because of his gcc version, not boost as such

**Comment by mvandeberg** [comment]
This appears to be caused by a gcc version, not a boost version.

**Comment by roadscape** [comment]
The doc still needs to be updated if boost 1.57 is no longer supported

**Pull request closed without merging**
