### PR TITLE
Issue #1824 - eliminating asset::to_string buffer overruns

### PR DESCRIPTION
**Pull request by vogel76**
Related to issue #1824

### CODE REVIEW

**Comment by theoreticalbts** [comment]
Let's change `to_string(buffer)` override as follows:

- Take `string&` instead of `string*`
- Be `public` not `private`, this is a perfectly well-defined method that we may want to use
- Get rid of `struct asset;` and `friend struct asset;`, it is a little confusing to have `asset_symbol_type` "know" something about `asset`, simpler if the dependency arrow points one way from `asset` to `asset_symbol_type`

**Comment by theoreticalbts** [comment]
- The digit for precision is a hex digit, not a decimal digit.  AFAICT this code doesn't function correctly for precision >= 10.
- Why have two helpers if `decimals()` is always a single digit?  Should just have one helper and pass in the number of decimals.
- Why two `to_decimal_string()` overrides?  Let's only have one instance of this function, if it means we can't avoid a memory allocation somewhere, that's OK.
- There's also a `helper` variable with an anonymous union type, I don't quite understand it.

**Comment by mvandeberg** [comment]
This branch still fails unit tests on OS X. Naively increasing the size of the buffer does solve the problem.

**Comment by vogel76** [comment]
@mvandeberg This code successfully passed valgrind and AddressSanitizer test on Linux where original don't. Could you provide callstack or more info related to crash ?

**Comment by vogel76** [comment]
@theoreticalbts Could you point me why this code fails with precision > 10 ?
Anyway to check it I did test and it fails in both: develop and this branch:
I have put this code at begin of `asset_symbol_validate`
```
   SMT_SYMBOL( alice12, 12);
   SMT_SYMBOL( alice11, 11);
   SMT_SYMBOL( alice10, 10);

   asset alice12a(12, alice12_symbol);
   asset alice11a(11, alice11_symbol);
   asset alice10a(10, alice10_symbol);

   auto ss12 = alice12_symbol.to_string();
   auto ss11 = alice11_symbol.to_string();
   auto ss10 = alice10_symbol.to_string();

   auto as12 = alice12a.to_string();
   auto as11 = alice11a.to_string();
   auto as10 = alice10a.to_string();

   asset a = asset::from_string(as12);
   BOOST_REQUIRE(a == alice12a);

   a = asset::from_string(as11);
   BOOST_REQUIRE(a == alice11a);

   a = asset::from_string(as10);
   BOOST_REQUIRE(a == alice10a);
```

**Comment by mvandeberg** [comment]
Same stack trace as in the issue.

**Comment by vogel76** [comment]
@mvandeberg Could you check that tested chain_test has been correctly rebuilt ? I suppose something was not recompiled and that's cause of same crash.

**Comment by mvandeberg** [comment]
I am 99.9% certain that I rebuilt because I do not normally have my dev env set to build SMTs, but need to to run this test. And I was working on several different branches at the time.

Regardless, I rebuilt and confirmed that the test case still fails on OS X. As stated earlier, the "naive" solution of simply increasing the buffer size solves the issue on OS X.

**Comment by mvandeberg** [comment]
Alright, it turns out it was my error. I went to dig into the code and realized my local branch didn't have any of the changes. Somehow it was not set to track the remote branch. Not sure how that happened. I probably fat fingered a command and broke my branch without realizing it.

It passes.

**Comment by vogel76** [comment]
@youkaicountry @theoreticalbts I have created separate issue #1888 for bug causing bad SMT asset serialization (independent to changes done in this branch). 
Please let me know what is wrong in code processing precision digit as @theoreticalbts commented:

> The digit for precision is a hex digit, not a decimal digit. AFAICT this code doesn't function correctly for precision >= 10.

I will also answer to other remarks too, but please first clarify potential functional issues.

**Comment by mvandeberg** [comment]
Due to the requirement for redoing all asset serialization, I am going to close this PR. It is not going to be a logical step towards the correct code.

**Pull request closed without merging**
