### PR TITLE
Removed invalid json from the default parameters of default_logger and default_appender

### LINKED ISSUE #2777: Buggy logging. Unexpected char '108' in "log-appender"
When starting steemd v0.19.11, this error is reported, with or without logging in the config.ini.

`1953549ms main.cpp:115                  main                 ] Error parsing logging config. Parse Error:Unexpected char '108' in "log-appender"`

- steemd file logging isn't working (it worked in 0.19.10).
- cli_wallet says `Logging RPC to file: logs/rpc/rpc.log` but nothing is happening there.
- logging level not obeyed, debug/warn/info all show the same things.

### PR DESCRIPTION
**Pull request by sgerbino**
Closes #2777.

### CODE REVIEW

**Comment by sgerbino** [comment]
Noted side effect: The logging configuration appears on 1 line.
```
# Appender definition json: {"appender", "stream", "file"} Can only specify a file OR a stream
log-appender = {"appender":"stderr","stream":"std_error"} {"appender":"p2p","file":"logs/p2p/p2p.log"}

# log-console-appender = 

# log-file-appender = 

# Logger definition json: {"name", "level", "appender"}
log-logger = {"name":"default","level":"info","appender":"stderr"} {"name":"p2p","level":"warn","appender":"p2p"}

```

**Comment by Jolly-Pirate** [comment]
I just tested this new version. 

```
steem_blockchain_version: 0.19.12
steem_git_revision:       54aa3bf2f4dff6da3f078eeccd25eeee7f2e2e4b
fc_git_revision:          54aa3bf2f4dff6da3f078eeccd25eeee7f2e2e4b
```

The `Parse Error:Unexpected char '108' in "log-appender"` error is gone. Although the log files are now created in logs/p2p/ they're 0 byte and not being populated.
```
p2p.log.20180820T180000
p2p.log
```

My config.ini has the following:
```
log-appender = {"appender":"stderr","stream":"std_error"} {"appender":"p2p","file":"logs/p2p/p2p.log"}
log-logger = {"name":"default","level":"info","appender":"stderr"} {"name":"p2p","level":"info","appender":"p2p"}
```

**Comment by sgerbino** [comment]
@Jolly-Pirate #2813 should fix this issue. Thanks for bringing this to my attention. Leave a comment there if you have time to verify the fix.

**Comment by Jolly-Pirate** [comment]
@sgerbino it's finally working! The file logger is writing to disk and the different log levels are working (debug, info, warn) 💯 

Tested in a dockerized build.

```
steem_blockchain_version: 0.19.12
steem_git_revision:       84fe87790a10f634842f5634e1c049b2976c7d91
fc_git_revision:          84fe87790a10f634842f5634e1c049b2976c7d91
```

**Pull request merged**
