### PR TITLE
Additional test scenarios of smt creation.

### PR DESCRIPTION
**Pull request by Kiwonik**
Added negative SMT creation cases. Also a separate commit fixes develop branch #1729

### CODE REVIEW

**Comment by Kiwonik** [comment]
I've just seen PR 1866 and dropped duplicating commit from the branch.

**Comment by mvandeberg** [comment]
CI is failing due to unrelated issue. Fixed in #1866 Please rebase on `develop`.

**Comment by youkaicountry** [comment]
I don't see any problems, should be able to approve after the rebase.

**Comment by Kiwonik** [comment]
Rebased. Redy to be merged again.

**Pull request merged**
