### PR TITLE
Disable bandwidth system

### LINKED ISSUE #3006: Remove old bandwidth system from witness plugin
Removing the old bandwidth system from the witness plugin will greatly simplify the code and should speed replays.

### PR DESCRIPTION
**Pull request by mvandeberg**
Closes #3006

### CODE REVIEW

**Comment by theoreticalbts** [comment]
LGTM

**Comment by bobinson** [comment]
@nedsteem : IMHO a plan to releasing this, timelines etc must be announced to the witnesses. And also, will it need a replay ?

**Comment by Smittyvb** [comment]
@bobinson Why? This will have no impact on Steem users, just cleaning up unused code.

**Comment by nedsteem** [comment]
With this change, Bandwidth, which is already deprecated and replaced by RCs, is functionally being commented out. No replay would be needed. The benefit of this however is any subsequent replays would occur faster due to not needing to calculate available bandwidths.

**Comment by bobinson** [comment]
Thank you @nedsteem  for the clarifications. The speed improvements are a welcome change and will save not just computational power but also save man hours spend as testing, deployment by witnesses everything will be lot more faster now.

@Smittyvb 

> Why?

Side effects, whether replay needed etc were not clear thus asked for the details.

>  This was already disabled, this just completely removes it from the code.

As discussed in #3029 we are not completely removing the code.

**Comment by KINGdotNET** [comment]
@nedsteem Are we expecting a new update/release anytime soon?

**Pull request merged**
