### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mvandeberg**
Update README.md for using CLI wallet in Docker.

### CODE REVIEW

**Comment by theoreticalbts** [comment]
These instructions won't work, they will store the file inside the Docker container which means THE USER WALLET WILL BE WIPED WHENEVER THE CONTAINER IS RESET.  If you're using `cli_wallet` with Docker, you need to mount an outside volume that will contain the user wallet.  Then we should instruct, perhaps repeatedly and PERHAPS IN ALL CAPS, that the user needs to keep multiple backups of their wallet file.

Also, the Docker container for the Steem wallet should not run steemd by default.  We should have separate containers for steemd and for the wallet (perhaps they inherit a common base container but the steemd container has startup scripts?)

Advice from Docker experts about this would be welcome @jredbeard @sneak

**Comment by jredbeard** [comment]
@theoreticalbts 

I'm sure those instructions do work, but yes, your wallet.json would be lost and not stored in an outside volume.

Personally, I don't want to ever keep a wallet.json around - for me it's one time use. Import keys, perform desired actions, remove. I'm assuming this is probably the case for most cli_wallet users. I have my doubts that anyone wants to keep a wallet.json around stored locally with their actual keys in it - I could be wrong, I suppose.

With all that being said, I think we should just mention that the stored wallet.json will be lost when the container exits - and modify the instructions to be a single command instead of launching a daemonized container and then stopping steemd. Example something like: `docker run -i -t steemit/steem /usr/local/steemd-full/bin/cli_wallet -s wss://steemd.steemit.com`

@sneak @mvandeberg comments welcome as well

**Comment by mvandeberg** [comment]
The wallet file being removed when the container is removed is fine. Maybe a note should be added about this behavior, but considering removing a docker container is an explicit action on behalf of the user, I do not view the behavior as a problem.

**Comment by theoreticalbts** [comment]
I'm closing this PR due to inactivity.  Additionally, nothing in these comments has addressed my main concern with approving this PR.  Namely, that it's a bad idea to recommend users configure their system in a way that will result in the silent and automatic deletion of their wallet.

**Comment by 4Ykw** [comment]
I agree with one thing. Having another docker for just the cli_wallet would ease the pain of some people.

**Comment by sneak** [comment]
Anyone who is experienced enough to use the cli_wallet can be trusted to manage their container lifecycles and volumes.

I don't want to spend much time on the cli_wallet.  Any advanced tooling around transaction creation should be focused on the python or js libraries.

**Comment by sneak** [comment]
The docker container's entrypoint can be overridden so that it *only* runs cli_wallet and no other processes.  There is no need for a separate image.

**Comment by jredbeard** [comment]
I think all that's necessary is the warning about your wallet.json being removed when the container is removed, and this one liner:

`docker run -it steemit/steem /usr/local/steemd-full/bin/cli_wallet -s wss://steemd.steemit.com`

The only frustrating thing about that is the 60s disconnect - because of that, it alternatively could be two lines:

```
docker run -it steemit/steem /bin/bash
/usr/local/steemd-full/bin/cli_wallet -s wss://steemd.steemit.com
```

That way you can easily restart it with the keys you've already imported if you miss the 60s disconnect time.

**Comment by mvandeberg** [comment]
This is made irrelevant by #1444

**Pull request closed without merging**
