### PR TITLE
Remove tags_api dependency from get_content

### LINKED ISSUE #2535: get_content is dependent on tags plugin
`get_content` should not have a hard dependency on `tags` or `follows` plugins.

`assert_exception: 'Assert Exception:_tags_api: tags_api_plugin not enabled.' in get_content(['avizor', 're-unknownmystery-re-avizor-re-unknownmystery-re-avizor-foodboasting-my-selmade-roastbeef-with-potatoes-20180530t202851030z'])`

### PR DESCRIPTION
**Pull request by mvandeberg**
Closes #2535

Should be merged after #2533

### CODE REVIEW

**Comment by mvandeberg** [comment]
Versions in `stable` for comparison:

`get_content`: https://github.com/steemit/steem/blob/stable/libraries/app/database_api.cpp#L982-L997
`get_active_votes`: https://github.com/steemit/steem/blob/stable/libraries/app/database_api.cpp#L999-L1030
`get_content_replies`: https://github.com/steemit/steem/blob/stable/libraries/app/database_api.cpp#L1139-L1155
`get_replies_by_last_update`: https://github.com/steemit/steem/blob/stable/libraries/app/database_api.cpp#L1163-L1199

**Comment by theoreticalbts** [comment]
Merge conflict, rebase?

**Comment by mvandeberg** [comment]
Merge conflict fixed in #2533

**Comment by theoreticalbts** [comment]
This duplicates the code in `get_active_votes`, `get_content_replies` and `get_replies_by_last_update`.  It's only a few lines, and all of these plugins will hopefully be deprecated anyway, so I don't consider this a blocker for merging this ticket.  But in theory, someday we should put this functionality in one place referenced by both plugins.

**Pull request merged**
