### PR TITLE
Re-implement plugin manifest code generator using Python + jinja2 #1157

### PR DESCRIPTION
**Pull request by theoreticalbts**
See #1157 for discussion

### CODE REVIEW

**Comment by theoreticalbts** [comment]
Oops, CMake doesn't like some of the new codegen when performing an out-of-tree build.  I know more-or-less what's wrong, will fix the build momentarily.

**Comment by mvandeberg** [comment]
Actually, before I merge this, I am getting several runtime errors when running cmake. I did this as a clean out of source build. It doesn't seem to occur on Linux. Compilation works and plugins are built, but can you at least look at the errors and if possible fix whatever is causing them?

```
/Users/mdv/Library/Homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py:125: RuntimeWarning: 'steem_manifest.plugins' found in sys.modules after import of package 'steem_manifest', but prior to execution of 'steem_manifest.plugins'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
-- PLUGINS_DEPS: /Users/mdv/git/steem/libraries/manifest/../plugins/account_by_key/plugin.json;/Users/mdv/git/steem/libraries/manifest/../plugins/account_history/plugin.json;/Users/mdv/git/steem/libraries/manifest/../plugins/account_statistics/plugin.json;/Users/mdv/git/steem/libraries/manifest/../plugins/auth_util/plugin.json;/Users/mdv/git/steem/libraries/manifest/../plugins/block_info/plugin.json;/Users/mdv/git/steem/libraries/manifest/../plugins/blockchain_statistics/plugin.json;/Users/mdv/git/steem/libraries/manifest/../plugins/debug_node/plugin.json;/Users/mdv/git/steem/libraries/manifest/../plugins/delayed_node/plugin.json;/Users/mdv/git/steem/libraries/manifest/../plugins/follow/plugin.json;/Users/mdv/git/steem/libraries/manifest/../plugins/market_history/plugin.json;/Users/mdv/git/steem/libraries/manifest/../plugins/private_message/plugin.json;/Users/mdv/git/steem/libraries/manifest/../plugins/raw_block/plugin.json;/Users/mdv/git/steem/libraries/manifest/../plugins/tags/plugin.json;/Users/mdv/git/steem/libraries/manifest/../plugins/witness/plugin.json

/Users/mdv/Library/Homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py:125: RuntimeWarning: 'steem_manifest.build' found in sys.modules after import of package 'steem_manifest', but prior to execution of 'steem_manifest.build'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
-- MANIFEST_DEPS: /Users/mdv/git/steem/libraries/manifest/templates/plugins/CMakeLists.txt.j2;/Users/mdv/git/steem/libraries/manifest/templates/plugins/mf_plugins.cpp.j2;/Users/mdv/git/steem/libraries/manifest/templates/plugins/plugins.cpp;/Users/mdv/git/steem/libraries/manifest/templates/plugins/include/steemit/manifest/plugins.hpp

/Users/mdv/Library/Homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py:125: RuntimeWarning: 'steem_manifest.build' found in sys.modules after import of package 'steem_manifest', but prior to execution of 'steem_manifest.build'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
-- MANIFEST_OUTPUTS: /Users/mdv/git/steem/build/libraries/manifest/gensrc/plugins/CMakeLists.txt;/Users/mdv/git/steem/build/libraries/manifest/gensrc/plugins/mf_plugins.cpp;/Users/mdv/git/steem/build/libraries/manifest/gensrc/plugins/plugins.cpp;/Users/mdv/git/steem/build/libraries/manifest/gensrc/plugins/include/steemit/manifest/plugins.hpp

/Users/mdv/Library/Homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py:125: RuntimeWarning: 'steem_manifest.plugins' found in sys.modules after import of package 'steem_manifest', but prior to execution of 'steem_manifest.plugins'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/Users/mdv/Library/Homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py:125: RuntimeWarning: 'steem_manifest.build' found in sys.modules after import of package 'steem_manifest', but prior to execution of 'steem_manifest.build'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
```

**Comment by theoreticalbts** [comment]
I was able to reproduce these warnings on Ubuntu 16.04 by the following procedure:

- Install Python 3.6.1 from tarball
- Create a new virtualenv with `-p` to point to Python 3.6.1 binary.
- `pip install jinja2` in the virtualenv
- `source bin/activate` to put Python 3.6.1 in `PATH`
- Run `cmake`

This means it's an issue in Python 3.6 (Ubuntu ships with 3.5.2).  It seems to be [this upstream issue](https://bugs.python.org/issue27487), some of the discussion there suggests previous versions may be less verbosely doing weird things and this warning was added so Python 3.6 would loudly complain.

Root cause seems to be both importing the module from `__init__.py` and running as `__main__` with the `-m` switch is an unsupported use case due to limitations in Python's import mechanism implementation.  Since we don't care too much about having them available in `__init__.py` we'll just remove the imports from there.

**Comment by theoreticalbts** [comment]
Added new commit to fix issue with braces in `newplugin.py`

**Pull request merged**
