### PR TITLE
Create common 'db_fixture' lib for 'chain_test' and 'plugin_test'

### PR DESCRIPTION
**Pull request by mkochanowicz**

### CODE REVIEW

**Comment by theoreticalbts** [comment]
Looks like rebase is required?

**Comment by mvandeberg** [comment]
This still wants to do the entire parallel API branch merge all over again. Reset your local branch to master and then cherry pick the commits from the feature branch on it.

**Comment by mkochanowicz** [comment]
I don't see where is a problem. I did merge 827 remote branch to master and there are no any conflicts. Could you explain what is wrong in current state of 827 branch, please?

**Comment by mvandeberg** [comment]
The diff for this commit has 74 commits, 21455 additions, and 9757 deletions. 

Rebased and replacing with #1369

**Pull request closed without merging**
