### PR TITLE
1510 surround smt objects evaluators and fields in ifdef

### PR DESCRIPTION
**Pull request by Kiwonik**
Implemented using separate STEEM_ENABLE_SMT flag and ENABLE_SMT_SUPPORT option  #1510

### CODE REVIEW

**Comment by theoreticalbts** [comment]
- `is_smt` field was removed from `account_object` in (the final merged version of) #1457, see https://github.com/steemit/steem/commit/a3d700f74dcb661b329321bf533705987b5f5c59

- Get rid of newly added `is_smt` and `FC_ASSERT( acct.is_smt == false, "The account has already been elevated." );` (the `is_smt` flag in the API object should stay).

Other than that, looks good.  This code needs a unit test, but I will file a separate issue for that.

**Comment by mvandeberg** [comment]
Let's add a build in Docker to test with SMT support. I will add an push to the branch

**Comment by Kiwonik** [comment]
Committed the changes related to `is_smt` as per  @theoreticalbts comments. Ready to merge. #1510

**Comment by mvandeberg** [comment]
This needs to be rebased on `develop`

**Comment by Kiwonik** [comment]
Cherry picked the changes to new branch with a new PR 1552. Closing this one, but not deleting to keep the comments history.

**Pull request closed without merging**
