### PR TITLE
Enable backtrace on segfault #1418

### PR DESCRIPTION
**Pull request by theoreticalbts**
PR for #1418

### CODE REVIEW

**Comment by mvandeberg** [comment]
Please make a PR in fc so that we always point to `master` in fc.

**Comment by theoreticalbts** [comment]
@mvandeberg I thought about doing that, but currently FC `master` has a bunch of parallel-api stuff, which I believe is non-backward-compatible.

**Comment by mvandeberg** [comment]
I tired to make as much of that backwards compatible as possible. Did you try merging locally and seeing if it works?

**Comment by mvandeberg** [comment]
I don't like having a branch that does not point to `fc/master` but there does appear to be some incompatibilities with `fc/master` and non-appbase steem branches. Considering that we will vendor in fc before the appbase release, I am going to less this one slide and merge with fc pointing to a branch.

**Pull request merged**
