### PR TITLE
Legacy asset serialization refactor #2003

### LINKED ISSUE #2003: Separate types for core vs plugin legacy asset serialization
As suggested in my review of #1993 I would like to see two different types: `legacy_steem_asset` as used in consensus for compatibility with invalid asset names that got into the chain due to checking on `chain_properties`, and `legacy_asset` in `condenser_api`.

### PR DESCRIPTION
**Pull request by theoreticalbts**
PR for #2003.  Needs testing.

### CODE REVIEW

**Comment by mvandeberg** [comment]
This branch does not build. Please build and test locally before creating a PR.

**Comment by theoreticalbts** [comment]
> Please build and test locally before creating a PR

I built `steemd`, didn't realize this might break tests.  My process is to build what's most likely to break, then let CI build the world.  That's what CI's for, right?

**Comment by mvandeberg** [comment]
This build is still failing.

**Comment by theoreticalbts** [comment]
Looks reasonable so far.

**Comment by theoreticalbts** [comment]
Looks good to me

**Pull request merged**
