### PR TITLE
Merge Appbase

### PR DESCRIPTION
**Pull request by mvandeberg**
PR to merge `develop` into `master` in prep for the Appbase release.

Below is the documented merge conflicts resolved in this branch.

```
both modified:   CMakeLists.txt
both modified:   Dockerfile
both modified:   README.md
both added:      contrib/config-for-broadcaster.ini
both modified:   contrib/config-for-docker.ini
both modified:   contrib/fullnode.config.ini
both modified:   contrib/paas-sv-run.sh
both modified:   contrib/startpaassteemd.sh
both modified:   contrib/sync-sv-run.sh
both modified:   doc/quickstart.md
both modified:   doc/seednodes.txt
deleted by them: libraries/app/api.cpp
deleted by them: libraries/app/application.cpp
deleted by them: libraries/app/database_api.cpp
deleted by them: libraries/app/include/steemit/app/api.hpp
deleted by them: libraries/app/include/steemit/app/database_api.hpp
both modified:   libraries/chain/block_log.cpp
both modified:   libraries/chain/database.cpp
both modified:   libraries/chain/include/steem/chain/steem_objects.hpp
both modified:   libraries/net/include/graphene/net/config.hpp
both modified:   libraries/net/include/graphene/net/node.hpp
both modified:   libraries/net/include/graphene/net/peer_connection.hpp
both modified:   libraries/net/node.cpp
both modified:   libraries/plugins/account_history/account_history_plugin.cpp
deleted by them: libraries/plugins/debug_node/debug_node_api.cpp
deleted by them: libraries/plugins/debug_node/include/steemit/plugins/debug_node/debug_node_api.hpp
both modified:   libraries/protocol/get_config.cpp
both modified:   libraries/protocol/include/steem/protocol/operation_util.hpp
both modified:   libraries/protocol/include/steem/protocol/operation_util_impl.hpp
deleted by them: libraries/protocol/include/steemit/protocol/config.hpp
both modified:   libraries/protocol/transaction.cpp
both modified:   programs/cli_wallet/CMakeLists.txt
both modified:   programs/steemd/CMakeLists.txt
```

These files should be closely scrutinized. The rest merged without issue and should be assumed good as they pass review when merged to `develop`. Please review the files that pertain to your area of expertise.

### CODE REVIEW

**Comment by mvandeberg** [comment]
Commit 28ab353 contains a fix for #1979, please review this commit specifically.

**Comment by theoreticalbts** [comment]
- I'm not reviewing anything in `contrib` because I don't really understand what it does.
- `doc/seednodes.txt` now has conflict

**Comment by theoreticalbts** [comment]
Other than the `seednodes.txt` conflict, everything in here looks good to me.

**Comment by youkaicountry** [comment]
Everything looks to me too.

**Pull request merged**
