### PR TITLE
2041 bmic replacement

### PR DESCRIPTION
**Pull request by mariusztrela**
**Design and implement boost::multi_index replacement basing on RocksDB storage #2041** 

- Create an unit test covering the container use cases #2288
- Implement custom iterators be responsible for providing data from one or more concatenated sources #2289
- Implement StorageConfigurationManager class providing functionality described in the architecture 'High level design of RocksDB based persistent layer' created by @vogel76  #2291

### CODE REVIEW

**Comment by mvandeberg** [comment]
Is it possible to split this into 3 PRs for each of the issues?

Even if some of them are dependent upon others, this would make reviewing the changes significantly easier. If there are dependencies, please document them in the PRs.

**Comment by vogel76** [comment]
I don't think so it is worth to split code into separate parts. This code does not affect application runtime right now since it is not yet live (not effectively used), We would like to merge it into develop to make code base current against develop changes and continue work on strict container replacement etc.

**Comment by mvandeberg** [comment]
I am asking to split it to make it easier to review each specific task. I understand why you want it merged. I have no problems with it. But I am not able to review this code as effectively as I could if it were split.

**Comment by mariusztrela** [comment]
I split this PR into 3 parts.

**Comment by mvandeberg** [comment]
Replaced by #2362, #2363, and #2364

**Pull request closed without merging**
