### PR TITLE
Issue #1683 - ( 'validate' methods  + unit tests )

### PR DESCRIPTION
**Pull request by mariusztrela**
Issue #1683 - first part

### CODE REVIEW

**Comment by theoreticalbts** [comment]
This code permits SMT <-> SBD market, but the spec calls for only SMT <-> STEEM market.

**Comment by theoreticalbts** [comment]
Currently `get_market()` basically returns some value such that `a.get_market() == b.get_market()` if and only if `a, b` involve the same pair of assets.  The current implementation does that fine with SMT's.  Why does it need to be replaced?

**Comment by theoreticalbts** [comment]
It's not written precisely the way I would have done, but it's mergeable.  Maybe I'll do a little refactoring later.

**Comment by mariusztrela** [comment]
a) According to `get_market` - you are right, I removed changes in this method.
b) According `market history plugin` - I made refactoring:
	- variable are embedded in structure `bucket_object_details`. It is more readable.
	- at now is new naming:
		earlier:	`steem <-> sbd`
		now:		`steem <-> sbd_smt`
	- I think, it is worth to add `asset_symbol_type symbol`, because we should know what symbols are put in `bucket_object`

**Comment by theoreticalbts** [comment]
The main concern here is template

We have this code:
```
   bucket_object_details steem;

#ifdef STEEM_ENABLE_SMT
   bucket_object_details sbd_smt;
#else
   bucket_object_details sbd;
#endif
```

Let's refactor to:

```
   bucket_object_details steem;
   bucket_object_details non_steem;
```

Then we can simplify out many of the `#ifdef` that were added in other places.

**Comment by theoreticalbts** [comment]
It is very confusing to have "template variable base class" of the form:

```
class B1 { ... };
class B2 { ... };

/* class C whose base class can be either B1 or B2 */
template< typename B >
class C : public B
{ ... };
```

A less jarring way to achieve this might be:

```
class B { ... };   /* abstract base class defining virtual methods for common functionality of B1, B2 */
class B1 : public B { ... };
class B2 : public B { ... };

/* class C who can use B1 or B2 */
class C
{
    ...
    B b;
};
```

I don't understand some bigger questions:

- (1) What is the difference between `database_fixture` and `clean_database_fixture`?
- (2) Why do you need to subclass both of them?

I suspect the answer to (2) is that "we don't really need to subclass both of them."  In the language of the example above, if `B2` is not actually ever needed, then it suffices to simply do:

```
class C : public B1 { ... };
```

**Comment by mariusztrela** [comment]
1) Refactoring - done. At now we have less `if-def's`.
	
2) I don't agree with you.
	 - Differences between `database_fixture` and `clean_database_fixture` are explained by @vandeberg in #1936. Shortly - constructor in `database_fixture` is empty, but constructor in `clean_database_fixture` does some initializations.

	- Further, the most tests use `clean_database_fixture`, but a few tests use `database_fixture`, because initialization is independent ( inside in given test ).
		
	- I proposed CRTP ( type of design pattern ) : `https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern`.
	  Above pattern solves such problem( inheritance from 2 different classes ) clearly and very readable.

**Comment by theoreticalbts** [comment]
Merge conflicts need to be fixed.

**Comment by mariusztrela** [comment]
Conflicts removed.

**Comment by youkaicountry** [comment]
There are further conflicts to be fixed before it can pass review.

**Comment by mariusztrela** [comment]
Done, no conflicts.

**Pull request merged**
