### PR TITLE
Rename some pack() / unpack() overrides #1940

### PR DESCRIPTION
**Pull request by theoreticalbts**
PR for #1940 .  New FC code in PR https://github.com/steemit/fc/pull/33

### CODE REVIEW

**Comment by theoreticalbts** [comment]
Force-pushed with some compile fixes.

**Comment by mvandeberg** [comment]
There are still build errors.

**Comment by mvandeberg** [comment]
Ah, crap. I forgot to merge fc changes first.

**Comment by mvandeberg** [comment]
Reviewed and merged fc changes. Can you make a new PR that bumps fc?

**Pull request merged**
