### PR TITLE
Implement testing scenarios related to smt create operation

### PR DESCRIPTION
**Pull request by Kiwonik**
Implemented testing scenarios of smt creation as described in issue 1653. Modified existing SMT operation tests to use created scenarios. #1653

### CODE REVIEW

**Comment by theoreticalbts** [comment]
The `create_smt_3()` function is re-used in several places to create 3 SMT's, but the code is a little strange:  it calls a callback with the symbols of the three created assets.  So you call it like this:

```
create_smt_3( ..., [&](const asset_symbol_type& smt1, const asset_symbol_type& smt2, const asset_symbol_type& smt3)
{
    // do something with smt1
    // do something with smt2
    // do something with smt3
} );
```

It seems easier to change `create_smt_3()` so it returns a `vector< asset_symbol_type >` of length 3, so the above code becomes:

```
vector< asset_symbol_type > sym = create_smt_3( ... );
// do something with sym[0]
// do something with sym[1]
// do something with sym[2]
```

**Comment by theoreticalbts** [comment]
I understand why you're adding the `by_nai` index.  You want to enforce this constraint:

- If some `smt_token_object` `obj` already exists with `obj.symbol.to_nai()` and `op.symbol.to_nai()` identical except for precision, the op should fail.

It turns out we can actually do that with just `by_symbol` index.

For every asset symbol `x` with an embedded precision value, we can define a related *canonical symbol* `CAN(x)` which is the same symbol, except the embedded precision value set to zero:

```
// return asset symbol with decimal places reset to zero
#define CAN(sym) \
   from_asset_num( sym.asset_num & 0xFFFFFFF0 )
```

Then our constraint becomes:

- If some `smt_token_object` `obj` already exists with `CAN(obj.symbol) == CAN(op.symbol)`, the op should fail.

Now `CAN(x)` has the same order as `asset_symbol_type`.  So it suffices to find the next element in the container greater than or equal to `CAN(x)`, which we can conveniently do with the `lower_bound()` function:

```
const auto& idx = _db.get_index< smt_token_index >().indices().get< by_symbol >();
auto it = idx.lower_bound( CAN( o.symbol ) );
```

If there are any objects in the container with `CAN(obj) == CAN(o.symbol)`, all such objects must be in a group together, and must start at `it`.  So we just trigger the exception when `it->symbol.asset_num == CAN( o.symbol )` like this:

```
FC_ASSERT( (it == idx.end()) || ( CAN( it->symbol.asset_num ) != CAN( o.symbol ) ), "SMT has already been created" );
```

**Comment by theoreticalbts** [comment]
I think I'll approve this, let's make separate issues for each of the above comments.

**Comment by youkaicountry** [comment]
I'll create issues for them.

**Comment by mvandeberg** [comment]
I want to see issues before merging this PR so they do not fall through the cracks.

**Comment by youkaicountry** [comment]
@mvandeberg Okay, I was waiting until this was merged to create them so they weren't immediately blocked. I'll make them shortly

**Comment by mvandeberg** [comment]
As soon as they are made, ping me and I'll merge the PR.

**Comment by youkaicountry** [comment]
@mvandeberg #1863 and #1864 have been created, go ahead and merge.

**Pull request merged**
