### PR TITLE
Fix varint unpack

### PR DESCRIPTION
**Pull request by mvandeberg**

### CODE REVIEW

**Comment by pmconrad** [comment]
I think changing unpack() can break consensus.

**Comment by mvandeberg** [comment]
In this case it does not. This particular change is to sanitize inputs from a varint larger than 32 bits. Yes, that input may be a block on the p2p network, but we deserialize it first and then when we check the signature we serialize, hash, and verify against that. Our serialization code is well formed so if serialization and deserialization are not symmetric (as they are prior to this fix) we will not have a matching signature. In order for a block to be accepted by consensus now it already needs to not break this rule.

**Comment by pmconrad** [comment]
Makes sense, thanks.

**Comment by theoreticalbts** [comment]
Looks reasonable.

**Pull request merged**
