### PR TITLE
JSON tuples condenser compat

### LINKED ISSUE #2254: JSON Tuples Condenser API Compatibility
#2075 changed some JSON serializations. A compatibility layer needs to be added for `condenser_api`.

### PR DESCRIPTION
**Pull request by mvandeberg**
Closes #2254

### CODE REVIEW

**Comment by theoreticalbts** [comment]
I guess this is an approximate summary of what this patch does:

- Implement a peer type for each `static_variant` which occurs anywhere in a legacy data structure.  (How are you sure you got them all?)
- Implement custom `to_variant()` / `from_variant()` serializers for each peer type, which delegate to `old_sv_(to|from)_variant`.
- As part of this process, implement a peer type for each *containing type* that directly or indirectly contains a member of any of the `static_variant` types you replaced above.  (A lot of types have now been replaced.)
- You now need some template magic in each containing type's assignment operator / constructor to convert between the peer (legacy) type and the current type.  This is implemented by `convert_(to|from)_legacy_static_variant`.

I'm still reviewing this.

**Comment by mvandeberg** [comment]
I am working on getting this deployed to dev as a smokescreen test that condenser is compatible with the changes.

**Comment by theoreticalbts** [comment]
Looks good, ready to merge.

**Comment by theoreticalbts** [comment]
Actually there is a little code that appears incomplete.  I filed a separate PR with a fix.

**Pull request merged**
