### PR TITLE
Unlimited content editing

### LINKED ISSUE #1714: Content cannot be edited after 7 days
Issue https://github.com/steemit/steem/issues/1266 was supposed to allow the editing of content older than 7 days after using `enable_content_editing` json with the active key. This still is not working. Could a change be made to just allow editing of all posts with just the posting key? If not, can `enable_content_editing` be fixed?

### PR DESCRIPTION
**Pull request by mvandeberg**
Closes #1714

### CODE REVIEW

**Comment by mvandeberg** [comment]
Force push to fix merge conflicts

**Comment by inertia186** [comment]
Verified using `radiator` to edit a post from 7 months ago:

https://steemd.com/@social/title-of-my-post
https://steemd.com/tx/bf0ac4396bac7dbbec6118632c913b86097b92c7

**Comment by inertia186** [comment]
Well, the edit was accepted but I guess it didn't take.

**Comment by feruzm** [comment]
It does change edit, but after multiple times... I suppose only api.steemit.com runs instance that supports edits (appbase), all other rpc won't work until next HF or upgrade to appbase

**Pull request merged**
