### PR TITLE
steemd sane defaults

### LINKED ISSUE #2176: UX: steemd does not start with sane defaults
Starting steemd without a `witness_node_data_dir` does not cause the blockchain to sync.  It should.  This means that seednodes should be compiled in, and should be populated in config.ini if and only if the config.ini doesn't exist and is being created.  If the config.ini already exists, the compiled-in seed nodes should be ignored.

### PR DESCRIPTION
**Pull request by mvandeberg**
Closes #2176

### CODE REVIEW

**Comment by mvandeberg** [comment]
This patch only changes the data-dir if not specified. I do not see any reason to change that in our Docker scripts. We weren't using `/some/random/path/witness_node_data_dir` anyway...

**Comment by mvandeberg** [comment]
I just realized this build is failing, will fix...

**Comment by mvandeberg** [comment]
@theoreticalbts Can I get your review on this as well, especially because I had to make changes after Justin's review?

**Comment by mvandeberg** [comment]
As stated in [this comment](https://github.com/steemit/steem/issues/2176#issuecomment-378971244), the requested behavior already exists in this branch.

**Comment by theoreticalbts** [comment]
Sorry, mis-read the code.  It all looks fine.

**Pull request merged**
