### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by TimCliff**
This pull request adds a file to the GitHub repository that shows a _"Please review the guidelines for contributing to this repository"_ message to users when they go to enter a new issue.

Here is an example of what it will look like:

image

When the user clicks the link, it will take them to this page where it shows the repository's guidelines for contributing. The text that will be shown on the page is below. (@sneak to review)

<HR>

## Please Read

Please read these instructions before submitting issues to the Steem GitHub repository. The issue tracker is for bugs and specific implementation discussion **only**. It should not be used for other purposes, as described below.

## Bug Reports

If there is an existing feature that is not working correctly, or a glitch in the blockchain that is impacting user behaviour - please open an issue to report variance. Include as much relevant information as you can, including screen shots or log output when applicable, and steps to reproduce the issue.

## Enhancement Suggestions

Do **not** use the issue tracker to suggest enhancements or improvements to the platform. The best place for these discussions is on Steemit.com. If there is a well vetted idea that has the support of the community that you feel should be considered by the development team, please email it to [sneak@steemit.com](mailto:sneak@steemit.com) for review.

## Implementation Discussion

The developers frequently open issues to discuss changes that are being worked on. This is to inform the community of the changes being worked on, and to get input from the community and other developers on the implementation.

Issues opened that devolve into lengthy discussion of minor site features will be closed or locked.  The issue tracker is not a general purpose discussion forum.

This is not the place to make suggestions for product improvement (please see the Enhancement Suggestions section above for this). If you are not planning to work on the change yourself - do not open an issue for it.

## Duplicate Issues

Please do a keyword search to see if there is already an existing issue before opening a new one.

## Steemit.com vs. Steem Blockchain

This issue tracker is only intended to track issues for the Steem blockchain. If the issue is with the Steemit.com website, please open an issue in the [Steemit.com Repository](https://github.com/steemit/steemit.com/).

## Pull Requests

Anybody in the community is welcome and encouraged to submit pull requests with any desired changes to the platform!

Requests to make changes that include working, tested pull requests jump to the top of the queue. There is not a guarantee that all functionality submitted as a PR will be accepted and merged, however.

### CODE REVIEW

**Comment by samupaha** [comment]
>Enhancement Suggestions

There should be an official tag for suggestions. Otherwise most of them will be not seen and therefore not discussed.

**Comment by mvandeberg** [comment]
I would rather create another issue tracker for suggestions. That way it is easier for us (the devs) to separate our workflow from suggestions. If github had support to link to Steem posts, then we could make a suggestions tag and be done with it. I don't want suggestions to be lost, but I also don't want them impeding my day to day workflow.

**Comment by TimCliff** [comment]
I see value in having a new GitHub repository to track all the community's suggestions, outside of the steem and condenser (formally steemit.com) repos. The main thing I _don't_ like about the idea is that it will likely pull a lot of the **discussion** of changes outside of Steemit and into GitHub.

Having semi-official tags that are used for suggestions (steem-suggestions and steemit-suggestions as an example) would be good, but getting people to use them is the difficult part.

**Comment by sneak** [comment]
I don't want to use GitHub for suggestions. I think it is ill-suited for it. We also won't have much bandwidth as a team for suggestions (outside of those pertaining to planned features on our roadmap) for several months.

**Comment by TimCliff** [comment]
Understood. Do we want any guidance in the GitHub "guidelines for contributing" as far as suggested tags for users to use when discussing suggestions on the platform, or should we just leave that up to the community to decide on their own?

**Comment by TimCliff** [comment]
@sneak - is the current version good, or are any changes needed?

**Pull request merged**
