### PR TITLE
Created claim_reward_balance2_operation.

### PR DESCRIPTION
**Pull request by Kiwonik**
Also added validation test and implemented evaluation. #1896

### CODE REVIEW

**Comment by youkaicountry** [comment]
Until it passes CI it can't be properly reviewed. Any idea what is causing it to fail?

**Comment by mvandeberg** [comment]
CI box was full. It has been cleaned up. Started build.

**Comment by theoreticalbts** [comment]
It's close, but see #2067

**Comment by mvandeberg** [comment]
Do we want to merge this or wait for #2067, @youkaicountry

**Comment by youkaicountry** [comment]
Let's not merge it yet, a structural change need to be made, so I'd rather not have it in the repo in this form yet.

The best way to proceed rather than modifying fc to allow use of a flat_set, is to use a vector and validate it. 

From #2067:
Use vector< asset > instead, and have validate() enforce reward_tokens[i].symbol > reward_tokens[i-1].symbol for all i > 0

**Pull request merged**
