### PR TITLE
Implemented smt_cap_reveal_operation

### PR DESCRIPTION
**Pull request by Kiwonik**
#1511
Uncovered some problems with setup operation implementation. Added dedicated pragmas and a new issue related to them (#2345)

### CODE REVIEW

**Comment by mvandeberg** [comment]
@youkaicountry Be aware of my review. I think some important SMT setup logic was not implemented and may have slipped through the cracks.

**Comment by Kiwonik** [comment]
@mvandeberg 
1. Here are the lines where cap reveal op checks the hash against the cap commitment from setup: ```o.cap.validate( smt.capped_generation_policy.min_steem_units_commitment );```
```o.cap.validate( smt.capped_generation_policy.hard_cap_steem_units_commitment );```
Naturally `o` is the cap reveal operation and `smt` is database token object where the hashes are stored by setup operation. These lines are taken from cap reveal operation evaluator.
1. Current setup operation implementation handles correctly hash commitments. They are stored in smt token object along with the rest of capped generation policy. Otherwise `smt_cap_reveal_apply` test would fail. You can see hash commitments being stored in token object in this snippet from `smt_evaluator.cpp` (merged by you to `develop` branch on March 22nd):
```
      _db.modify( _token, [&]( smt_token_object& token )
      {
         token.capped_generation_policy = capped_generation_policy;
      });
```
3. On your request I extended `smt_cap_reveal_apply` test negative cases with revealed caps (or nonce) not matching the committed hashes.
4. Having said all of that I do not see any missing "important SMT setup logic". At least none that would affect cap reveal implementation or testing.
5. The problems of setup operation that I failed to described clearly in #2345 (for which I apologize) do not affect cap reveal implementation or testing either. I expanded the description there.

**Comment by mvandeberg** [comment]
@theoreticalbts I would like your review as well.

**Comment by theoreticalbts** [comment]
Looks reasonable.

**Pull request merged**
