### PR TITLE
Fix denominator in vote_evaluator computation #1285

### PR DESCRIPTION
**Pull request by theoreticalbts**
Guide to review:

- The first commit does the new computation but throws away the result, except for printing a message when it does not match the old computation.
- The second commit throws away the old computation and only does the new computation.

If we replay the blockchain with the first commit only, and verify that the message is not printed, then the PR is valid and ready to merge.  I'm currently replaying and verifying this.

### CODE REVIEW

**Comment by theoreticalbts** [comment]
Effectively we have an expression of the form `a/(b*(c/d))`, where `c/d` has no remainder.  Since the outer division may have a remainder, we transform this to `round(a / (b*(c/d)) )` where `round()` is the rounding used (which was changed in #259).  Since `c/d` is the same in integer vs. rational-number division, we can transform the entire expression inside `round()` using normal (rational-number) algebraic manipulations.  Thus `round(a / (b*(c/d)) ) = round(a*d / (b*c))`.

The above line of reasoning proves that this patch is valid when applied with these substitiutions:

```
a = (current_power * abs_weight) / STEEMIT_100_PERCENT
b = dgpo.vote_power_reserve_rate
c = STEEMIT_VOTE_REGENERATION_SECONDS
d = (60*60*24)
```

**Comment by NateBrune** [comment]
I feel like a unit test might be in order to make sure this doesn't happen again.

**Comment by mvandeberg** [comment]
The unit test that checks vote power is sufficient to test this, specifically `opertation_tests/vote_apply` still has the old expression and the unit test passes, showing the expressions are equivalent (at least on the given input). Looks like a self-contained patch. I assume the reindex of this branch was successful?

**Comment by theoreticalbts** [comment]
I'm pretty sure it was successful, but I suppose I could re-run it.

**Pull request merged**
