### PR TITLE
Create API using DRY principles #1384

### PR DESCRIPTION
**Pull request by theoreticalbts**

### CODE REVIEW

**Comment by theoreticalbts** [comment]
Actually...this isn't working for some reason, investigating.

**Comment by theoreticalbts** [comment]
Looks like my troubles were due to:

- I copied and used an old config file, it really, really isn't backward compatible at this point #1297
- Blindly using `--replay-blockchain` #1386
- `test_api_plugin` doesn't use `DECLARE_API` macros, now fixed in this branch

**Comment by theoreticalbts** [comment]
Needs to be rebased before merge due to conflict with #1395

**Comment by mvandeberg** [comment]
Merge conflict, please rebase or merge `develop`

**Comment by theoreticalbts** [comment]
Rewrote this bit-rotted patch (well, it was mostly a copy-paste job, but enough stuff needed to be changed that `git rebase` wasn't quite up to the task).  It now works with latest `develop`.

**Pull request merged**
