### PR TITLE
get_dev_key: show help if less than 2 parameters are given #1756

### PR DESCRIPTION
**Pull request by theoreticalbts**
Local PR for #1756

### CODE REVIEW

**Comment by mvandeberg** [comment]
Do we want to merge #1737 first to see if there is a merge conflict?

**Comment by youkaicountry** [comment]
Sure, go ahead and do that. It doesn't look like there should be any problems though.

**Comment by piem** [comment]
Hi @youkaicountry sorry I had not seen #1737. It seems there will be a conflict, but it should be fairly easy to merge. Let me know if you want me to do something about it.

**Comment by mvandeberg** [comment]
@theoreticalbts Please rebase on develop

**Comment by piem** [comment]
@theoreticalbts FYI, I've just merged develop into my branch [getdevkey](/piem/steem/tree/getdevkey)

cheers, piem

**Pull request merged**
