### PR TITLE
Restore `get_ticker` functionality

### LINKED ISSUE #1926: Restore `get_ticker` functionality
In #1571, `get_ticker` was changed so it could compile with changes to `asset`. It needed to be refactor to use a local version of `to_real` as documented in the issue.

An issue to do this refactor was not made and the commented code was subsequently removed in https://github.com/steemit/steem/commit/24a9c155161566945612854ffe15be3fd1e7f76e#diff-ed4afb98aca7b45c93aab1ab6a54ac10

It needs to be restored to its original functionality.

### PR DESCRIPTION
**Pull request by mvandeberg**
Closes #1926

### CODE REVIEW

**Comment by theoreticalbts** [comment]
This line raises a couple issues:

```
result.percent_change = ( (result.latest - open ) / open ) * 100;
```

- Should be `STEEM_100_PERCENT` instead of `100`, allowing us to give two decimal places rather than be limited to integer precision
- The result of the division will be between 0 and 1, since it's integer math the result will always be zero, so we have to do the multiplication first.

To summarize, the calculation should be

```
(STEEM_100_PERCENT * (result.latest - open) ) / open
```

**Comment by mvandeberg** [comment]
Because this is a non-consensus API, both `latest` and `percent_change` are doubles.

**Comment by mvandeberg** [comment]
@theoreticalbts Is this PR mergeable?

**Comment by theoreticalbts** [comment]
I guess if they're both `double` we can go ahead and merge it.

**Pull request merged**
