### PR TITLE
Make build dir read-only before running tests #1562

### PR DESCRIPTION
**Pull request by theoreticalbts**
PR for #1562.  This should not pass CI until a fix for #1561 is available, and should not be merged until it passes CI.

When such a fix is available, rebase this PR on the fix.  Then if CI passes for the rebased PR, the fix is valid, and both #1561 and #1562 can be closed once the rebased PR is merged to `develop`.

### CODE REVIEW

**Comment by mvandeberg** [comment]
I thought this branch was not supposed to pass CI

**Comment by theoreticalbts** [comment]
Good point.  I wonder why it does?

**Comment by mvandeberg** [comment]
What is the status of this? It should fail CI right now and is not, but has not been touched in over 2 months.

**Comment by mvandeberg** [comment]
Closing until we begin working on this again.

**Pull request closed without merging**
