### PR TITLE
Steem Soft Fork 0.22.5

### PR DESCRIPTION
**Pull request by steemitofficial**
This soft (hard) fork undoes the changes of 0.22.2 and unlocks everyone's stake after the hardfork time.

### CODE REVIEW

**Comment by noisy** [comment]
Why you are make it public? You don't need approval from anyone right now... so why you pretend you care about openness and decentralization?

**Comment by netuoso** [comment]
You could have just deleted the code you absolute fucking idiots. Was this soft fork reversal done by a three year old?

Ladies and gentlemen, these idiots left "malicious code" in their Blockchain when it could have literally just been deleted. What a bunch of dumbasses

**Comment by VIM-Arcange** [comment]
They hired a new dev: welcome to hell Joe Smith

**Comment by netuoso** [comment]
They could have just used the existing branch on the steemit repo for 0.22.x. These idiots are retarded. Good luck for any dev work to be accomplished on Steem going forward with these quality devs lmao

**Comment by sneak** [comment]
> `From: Joe Smith <email@example.com>`

I think he'll be okay.

**Comment by skzap** [comment]
@noisy it obviously needs to be public, otherwise users cannot trust the nodes for their transactions (exchanges for example). Close-source and blockchain doesn't really go well together you know

**Comment by netuoso** [comment]
Code being "public" on GitHub provides NO VERIFICATION that code is actually being ran in production. You might know this if you were actually a developer @skzap

**Comment by techcoderx** [comment]
yeah the code on open source platforms does not reflect what code people run on servers at all

**Comment by skzap** [comment]
@netuoso If code is available, I can run an observer node and check if some transactions are not included and things like that. So not really.

No need to be salty with me @netuoso btw, I'm not part of SteemIt inc. Good job getting your 10 lines of code in production for about a week though.

**Comment by netuoso** [comment]
@skzap you realize they could have used the existing code on the repo to revert the fork right? I know you are a dumbass but you aren't that dumb I suspect. There is zero reason for this code to remain in production except for the fact that these idiots responsible don't know Blockchain programming.

**Comment by skzap** [comment]
The code change is obviously retarded. A good dev rushing would have taken a shorter route too. But hey, in the end it does the same thing doesn't it, and it works? Probably good enough for people running it, and they have witness votes majority, so be it ... Those are the risks of DPOS

**Comment by netuoso** [comment]
They have witness vote majority for fraudulently using customer funds on exchanges. And there isn't 20 witness servers, there is a single witness server with 20 witnesses configured to it. 

What a wonderful stable and secure blockchain they provided.

**Comment by Namiks** [comment]
Is this the Chinese fuckery comment section I've heard about? Is it CCP approved?

**Comment by sneak** [comment]
@netuoso, I encourage you to stop being so rude to people.  You undermine your own efforts.  Be kind, especially and foremost to the ignorant.

That's also not what "fraudulently" means.

**Comment by propertunist** [comment]
@Sneak It's good that you seem to have moved on from your previous approach of telling Steem users to 'die in a fire' while working for Steemit inc.

**Comment by netuoso** [comment]
@sneak lmao have you found god recently? You are still a joke don't fool yourself.

**Comment by Joythewnderer** [comment]
fuck u very much steemit and joe smith

**Comment by Joythewnderer** [comment]
> @netuoso, I encourage you to stop being so rude to people. You undermine your own efforts. Be kind, especially and foremost to the ignorant.
> 
> That's also not what "fraudulently" means.

said someone who contribute much less efforts

**Comment by pfunks** [comment]
This is the software equivalent of June Fourth in the Tiananmen Square protests of 1989. Although at least thousands of young students weren't murdered and ground to a bloody pulp under the treads of tanks in this instance.

**Comment by Jolly-Pirate** [comment]
You could have just used the 0.22.1 code, even a 5-year old could have figured that out.

**Comment by tngflx** [comment]
actually who is the one have access to gihub repo? who decides if this pr pass the request? is it vanderberg?

**Comment by mahdiyari** [comment]
Gavin, Gavin!
I'm looking for Gavin
He's lost since 1899
I thought he might be here!
- Gavin's friend

p.s. https://youtu.be/26U9HjWSFmo?t=30

**Pull request closed without merging**
