### PR TITLE
get_discussions_by_blog to filter resteems

### PR DESCRIPTION
**Pull request by thebitcoiner**
For issue #581

Post: https://steemit.com/steemit/@bitcoiner/resteemed-tab-has-been-developed-with-steemd-backend-change

### CODE REVIEW

**Comment by mvandeberg** [comment]
@jcalfee Are these changes to `get_state` something you want?

**Comment by roadscape** [comment]
@mvandeberg yes. The goal is to allow us to fetch either a pure blog or pure resteemed feed while maintaining backwards-compatibility.

**Comment by jcalfee** [comment]
@mvandeberg I think it is a great idea to split up blogs and resteems this gives authors some freedom to re-steem a lot and still lets users easily find their personal material.

I'm going to have to build this branch before I understand the changes though.

**Comment by thebitcoiner** [comment]
Correct, this implementation maintains backwards compatibility. A get_state @user and get_discussions_by_blog functions as it used to. For 6 examples of various usage, see the related steemit post.

**Pull request merged**
