### PR TITLE
Account Subsidy Limit

### PR DESCRIPTION
**Pull request by mvandeberg**
#closes 1765

### CODE REVIEW

**Comment by theoreticalbts** [comment]
No code has been written which reads this property.  Is that going to be in a future PR?

**Comment by mvandeberg** [comment]
Yes, the implementation of your egg proposal will be another PR. I am trying to make issues small and modular to make reviewing PRs easier.

**Comment by theoreticalbts** [comment]
> I am trying to make issues small and modular to make reviewing PRs easier.

Yeah, this was simple to review.  Just making sure we don't lose track that code needs to be written.

**Comment by mvandeberg** [comment]
Issues are already made for the later implementation.

**Pull request merged**
