### PR TITLE
Issue #1949 - account history optimizations.

### PR DESCRIPTION
**Pull request by mariusztrela**
Issue #1949

### CODE REVIEW

**Comment by mvandeberg** [comment]
Do you have performance information on this patch?

I would specifically like reindex and resync performance for this change. By having each account's history in a single object, when it is updated, the entire account history will be copied. This is an O(n) copy. When we are live, accounts can have 1000s of operations in their history. Specifically, I am interested in potential overhead breakpoints. I agree that having the entire history in a single object is more space efficient, but I am worried about performance overhead when live.

**Comment by mariusztrela** [comment]
****************
- branch:	1949-account-history-opt2
- commit:	f6431d2
- type:		replay
-- total( hours ): 13.2

- branch:	develop
- commit:	6df95a8
- type:		replay
-- total( hours ): 14.7

****************
- branch:	1949-account-history-opt2
- commit:	f6431d2
- type:		replay-nofollow.log
- others:	switch `follow-start-feeds` enabled
-- total( hours ): 4.5

- branch:	develop
- commit:	6df95a8
- type:		replay
- others:	switch `follow-start-feeds` enabled
-- total( hours ): 5.32

****************
- branch:	1949-account-history-opt2
- commit:	f6431d2
- type:		resync
-- total( hours ): 31.72

- branch:	develop
- commit:	6df95a8
- type:		resync
-- total( hours ): 31.78

****************

**Comment by mariusztrela** [comment]
In `resync`, it seems, that measurement is covered by time of p2p operations. Anyway, there is no slowdown.
Technical information: done on `r4.8xlarge` ( AWS ). If it is necessary, I can give logs from these benchmarks.

**Comment by vogel76** [comment]
@mvandeberg Could you take a look on it ? Performance is not worse during resync as it does similar actions as reindex (which faster) plus network communication where most of the time is spent.

**Comment by mvandeberg** [comment]
Rebased and force pushed to resolve conflicts.

**Comment by mvandeberg** [comment]
Rebasing this has some tricky merge conflicts. It would appear that I made a mistake. I will have time to fix it next week unless you get to it before then.

**Comment by vogel76** [comment]
I think this PR is obsolete right now because AH implementation shall be replaced by work done in:
https://github.com/steemit/steem/pull/2129
@youkaicountry Please close this PR if you also agree.

**Comment by youkaicountry** [comment]
I definitely agree. This is deprecated in favor of #2129. Closing.

**Pull request closed without merging**
