### PR TITLE
change moment of p2p::set_block_production call in witness plugin

### PR DESCRIPTION
**Pull request by mkochanowicz**
Issue #2205

### CODE REVIEW

**Comment by abitmore** [comment]
IMHO this changed too much.

The original logic was: if witness_plugin is enabled, while syncing, the node will validate signatures of all transactions.

After this change, before caught up (in sync), the node won't validate signatures.

**Comment by mkochanowicz** [comment]
@abitmore Node start validate signatures after sync completed. Is it wrong?

**Comment by abitmore** [comment]
@mkochanowicz: block producing nodes (whose witness list is non-empty) should validate every block it received. We favor security over performance in this case.

Non-block-producing nodes (whose witness list is empty) can skip signature validation for better performance while syncing.

**Comment by mkochanowicz** [comment]
@abitmore So, I can do sync with empty witnesses list (non-block-producing node), then restart `steemd` with built state and with non-empty witnesses list (block-producing node) - if I we talk about pre-abbase. My code changes is simply shortcut for such solution.

Maybe change in appbase is intentional, to disable such scenario? @mvandeberg ?

**Pull request merged**
