### PR TITLE
1999 follow plugin

### PR DESCRIPTION
**Pull request by mariusztrela**
#1999

### CODE REVIEW

**Comment by mvandeberg** [comment]
I am getting segfaults on this branch when I am getting blocks live. Due to long reindex times and unexpected segfault, I was not running steemd in a debugger. I will reindex again in the debugger (tonight so it works while I sleep) and will get you results then.

**Comment by vogel76** [comment]
@mvandeberg Can I ask for config.ini and build configuration (cmake settings). We would lilke to run it also. Maybe do you have at least stacktrace produced by SIGSEGV handler ?

**Comment by mvandeberg** [comment]
Relevant config options

`plugin = webserver p2p json_rpc follow`

`plugin = database_api condenser_api follow_api`

`follow-max-feed-size = 500`

`follow-start-feeds = 1516664004`

I apologize for not having a stack trace. The built in stack dump does not work on OS X. The only way I can get a stack trace is running in lldb. I was not because I was not expecting a stack trace. Reindex works fine. It crashed when some time after going live. As I said, I can reindex tonight in the debugger and get you a stack trace.

**Comment by vogel76** [comment]
@mvandeberg Thanks, steemd was built as fullnode or low-mem-node ?

**Comment by mvandeberg** [comment]
`-D LOW_MEMORY_NODE=ON -D CLEAR_VOTES=ON`

**Comment by mvandeberg** [comment]
I apologize for having been silent on this review. Running with the debugger was not helpful. My node got stuck in an infinite loop while allocating memory. It did get stuck in a follow plugin data structure which may help lead to discovering the source of this bug.

screen shot 2018-02-05 at 08 00 20

I have added functionality to fc to dump the stacktrace in OS X in an OS X idiomatic way so I do not need to rely on the inconsistent behavior of the debugger. Previously, this was only enabled for Linux with gcc, was incompatible with OS X and clang, and was skipped via ifdef for OS X. I am reindexing again with said changes and will update when I have more information.

**Comment by mvandeberg** [comment]
```
0   steemd                              0x000000010be4b000 _ZN2fc16print_stacktraceERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEjPv + 80
1   steemd                              0x000000010be4af69 _ZN2fc16segfault_handlerEi + 41
2   libsystem_platform.dylib            0x00007fff6ae93f5a _sigtramp + 26
3   ???                                 0x000000011a575630 0x0 + 4736898608
4   steemd                              0x000000010b76780e _ZN5boost11multi_index21multi_index_containerIN5steem7plugins6follow11feed_objectENS0_10indexed_byINS0_14ordered_uniqueINS0_3tagINS2_5chain5by_idEN4mpl_2naESC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_EENS0_6memberIS5_N9chainbase3oidIS5_EEXadL_ZNS5_2idEEEEESC_EENS7_INS8_INS4_7by_feedESC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_EENS0_13composite_keyIS5_NSE_IS5_NS2_8protocol17fixed_string_implIN2fc7uint128EEEXadL_ZNS5_7accountEEEEENSE_IS5_jXadL_ZNS5_15account_feed_idEEEEENS_6tuples9null_typeESV_SV_SV_SV_SV_SV_SV_EENS0_21composite_key_compareINSt3__14lessISR_EENSY_7greaterIjEESV_SV_SV_SV_SV_SV_SV_SV_EEEENS7_INS8_INS4_10by_commentESC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_EENSM_IS5_NSE_IS5_NSG_INS9_14comment_objectEEEXadL_ZNS5_7commentEEEEESS_SV_SV_SV_SV_SV_SV_SV_SV_EENSX_INSZ_IS18_EES10_SV_SV_SV_SV_SV_SV_SV_SV_EEEESC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_SC_EENS_12interprocess9allocatorIS5_NS1F_15segment_managerIcNS1F_15rbtree_best_fitINS1F_12mutex_familyENS1F_10offset_ptrIvlmLm0EEELm0EEENS1F_10iset_indexEEEEEE7modify_IZNSF_13generic_indexIS1Q_E4undoEvEUlRS5_E_EEbRT_PNS0_6detail18ordered_index_nodeINS1Y_19null_augment_policyENS1Z_IS20_NS1Z_IS20_NS1Y_15index_node_baseIS5_S1P_EEEEEEEE + 126
5   steemd                              0x000000010b767175 _ZN9chainbase13generic_indexIN5boost11multi_index21multi_index_containerIN5steem7plugins6follow11feed_objectENS2_10indexed_byINS2_14ordered_uniqueINS2_3tagINS4_5chain5by_idEN4mpl_2naESE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_EENS2_6memberIS7_NS_3oidIS7_EEXadL_ZNS7_2idEEEEESE_EENS9_INSA_INS6_7by_feedESE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_EENS2_13composite_keyIS7_NSG_IS7_NS4_8protocol17fixed_string_implIN2fc7uint128EEEXadL_ZNS7_7accountEEEEENSG_IS7_jXadL_ZNS7_15account_feed_idEEEEENS1_6tuples9null_typeESW_SW_SW_SW_SW_SW_SW_EENS2_21composite_key_compareINSt3__14lessISS_EENSZ_7greaterIjEESW_SW_SW_SW_SW_SW_SW_SW_EEEENS9_INSA_INS6_10by_commentESE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_EENSN_IS7_NSG_IS7_NSH_INSB_14comment_objectEEEXadL_ZNS7_7commentEEEEEST_SW_SW_SW_SW_SW_SW_SW_SW_EENSY_INS10_IS19_EES11_SW_SW_SW_SW_SW_SW_SW_SW_EEEESE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_EENS1_12interprocess9allocatorIS7_NS1G_15segment_managerIcNS1G_15rbtree_best_fitINS1G_12mutex_familyENS1G_10offset_ptrIvlmLm0EEELm0EEENS1G_10iset_indexEEEEEEEE4undoEv + 965
6   steemd                              0x000000010b765a46 _ZN9chainbase12session_implINS_13generic_indexIN5boost11multi_index21multi_index_containerIN5steem7plugins6follow11feed_objectENS3_10indexed_byINS3_14ordered_uniqueINS3_3tagINS5_5chain5by_idEN4mpl_2naESF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_EENS3_6memberIS8_NS_3oidIS8_EEXadL_ZNS8_2idEEEEESF_EENSA_INSB_INS7_7by_feedESF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_EENS3_13composite_keyIS8_NSH_IS8_NS5_8protocol17fixed_string_implIN2fc7uint128EEEXadL_ZNS8_7accountEEEEENSH_IS8_jXadL_ZNS8_15account_feed_idEEEEENS2_6tuples9null_typeESX_SX_SX_SX_SX_SX_SX_EENS3_21composite_key_compareINSt3__14lessIST_EENS10_7greaterIjEESX_SX_SX_SX_SX_SX_SX_SX_EEEENSA_INSB_INS7_10by_commentESF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_EENSO_IS8_NSH_IS8_NSI_INSC_14comment_objectEEEXadL_ZNS8_7commentEEEEESU_SX_SX_SX_SX_SX_SX_SX_SX_EENSZ_INS11_IS1A_EES12_SX_SX_SX_SX_SX_SX_SX_SX_EEEESF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_SF_EENS2_12interprocess9allocatorIS8_NS1H_15segment_managerIcNS1H_15rbtree_best_fitINS1H_12mutex_familyENS1H_10offset_ptrIvlmLm0EEELm0EEENS1H_10iset_indexEEEEEEEE7sessionEED0Ev + 38
7   steemd                              0x000000010b74b33f _ZNSt3__16vectorINS_10unique_ptrIN9chainbase16abstract_sessionENS_14default_deleteIS3_EEEENS_9allocatorIS6_EEED1Ev + 63
8   steemd                              0x000000010b74b2f3 _ZN9chainbase8database7sessionD2Ev + 211
9   steemd                              0x000000010b999878 _ZN5steem5chain8database13clear_pendingEv + 296
10  steemd                              0x000000010b9b2956 _ZN5steem5chain8database10push_blockERKNS_8protocol12signed_blockEj + 550
11  steemd                              0x000000010b993378 _ZN5steem7plugins5chain12chain_plugin12accept_blockERKNS_8protocol12signed_blockEbj + 872
12  steemd                              0x000000010b82c1f5 _ZN5steem7plugins3p2p6detail15p2p_plugin_impl12handle_blockERKN8graphene3net13block_messageEbRNSt3__16vectorIN2fc9ripemd160ENS9_9allocatorISC_EEEE + 2165
13  steemd                              0x000000010b92fa4b _ZN2fc6detail11functor_runIZN8graphene3net6detail42statistics_gathering_node_delegate_wrapper12handle_blockERKNS3_13block_messageEbRNSt3__16vectorINS_9ripemd160ENS9_9allocatorISB_EEEEE4$_57E3runEPvSI_ + 59
14  steemd                              0x000000010be3ed80 _ZN2fc9task_base8run_implEv + 48
15  steemd                              0x000000010be3a981 _ZN2fc8thread_d13run_next_taskEv + 129
16  steemd                              0x000000010be365a8 _ZN2fc8thread_d13process_tasksEv + 360
17  steemd                              0x000000010be35fd3 _ZN2fc6thread4execEv + 275
18  steemd                              0x000000010be3ce04 _ZN5boost6detail11thread_dataIZN2fc6threadC1ERKNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEEE3$_0E3runEv + 100
19  steemd                              0x000000010bf2cb2b _ZN5boost12_GLOBAL__N_1L12thread_proxyEPv + 155
20  libsystem_pthread.dylib             0x00007fff6ae9d6c1 _pthread_body + 340
21  libsystem_pthread.dylib             0x00007fff6ae9d56d _pthread_body + 0
22  libsystem_pthread.dylib             0x00007fff6ae9cc5d thread_start + 13
```

It looks like the infinite loop in the debugger is where the segfault occurred.

**Comment by mariusztrela** [comment]
I had generated a lot of logs, before I realized, that additional field in multi_index is necessary. It is caused, because during `undo` operation, sometimes object in `old_values` collection has the same set of keys as another object in state. I saw identical solution in a few places in whole project.

**Comment by mariusztrela** [comment]
Tests:
reindex - `works`
retrieving actual blocks from nodes - `works`

**Comment by vogel76** [comment]
Part of changes done here is also related to issue #1950. Since this PR has been thoroughly verified, please merge it as fast as possible to make possible work further on #1950

**Comment by mvandeberg** [comment]
Rebased on `develop` to resolve merge conflicts

**Comment by mvandeberg** [comment]
My local testing indicates this branch is stable, can reindex, and keep up with live network.

**Pull request merged**
