### PR TITLE
fix zero voting power

### PR DESCRIPTION
**Pull request by mvandeberg**
Local PR for #3218

### CODE REVIEW

**Comment by economicstudio** [comment]
@mvandeberg Thank you for your quick response. But why the check has failed? I don't see any problem and I can't see the log. Is there any way, that I can do that check locally? I made some contributions to busy.org and it provides some checking procedure before commit, which is very convenient. I'd like to know if there is such for steem. Thanks!

**Comment by mvandeberg** [comment]
From our CI server:

> Build tests] /usr/local/src/steem/libraries/plugins/apis/condenser_api/condenser_api.cpp: In member function ‘uint16_t steem::plugins::condenser_api::api_account_object::_compute_voting_power(const steem::plugins::database_api::api_account_object&)’:
> [Build tests] /usr/local/src/steem/libraries/plugins/apis/condenser_api/condenser_api.cpp:2085:8: error: ‘vt_t2u’ was not declared in this scope
> [Build tests]     if( vt_t2u == 0 )
> [Build tests]         ^
> [Build tests] /usr/local/src/steem/libraries/plugins/apis/condenser_api/condenser_api.cpp:2095:29: error: ‘const struct steem::plugins::database_api::api_account_object’ has no member named ‘voting_power’
> [Build tests]     return vp_t1 ? vp_t1 : a.voting_power;

**Comment by economicstudio** [comment]
@mvandeberg Thanks! I'll check it out and resubmit.

**Comment by economicstudio** [comment]
Is there a way to add commit to previous pull request? I tried, but I couldn't, so I made a new PR: #3221 
Thanks.

**Pull request closed without merging**
