### PR TITLE
Issue #1312 - plugin pointer type consistemcy

### PR DESCRIPTION
**Pull request by mariusztrela**
#1312

### CODE REVIEW

**Comment by mvandeberg** [comment]
Merge conflicts

**Comment by theoreticalbts** [comment]
When do we use `shared_ptr` vs `unique_ptr`?  In this patch some use `unique_ptr` (`account_by_key_plugin`, `account_history_plugin`) while others use `shared_ptr` (`block_api`, `chain_api`, `condenser_api`).

I thought the point of the issue was to pick one of these two pointer types and use it for `my` member of all plugins.

**Comment by mvandeberg** [comment]
I think following the impl pattern should all be private unique pointers.

The APIs should be shared pointers because, unlike FC APIs, these APIs are singletons.

**Comment by mariusztrela** [comment]
Done.

**Pull request merged**
