### PR TITLE
Move broadcast_transaction_synchronous to condenser_api

### LINKED ISSUE #2278: Move `broadcast_transaction_synchronous` to `condenser_api`
We want to move away from synchronous transaction broadcasting to polling via the transaction confirmation proposal (#486).

The existing `broadcast_transaction_synchronous` call should be moved to `condenser_api` in preparation to become deprecated.

### PR DESCRIPTION
**Pull request by mvandeberg**
Closes #2278

### CODE REVIEW

**Comment by theoreticalbts** [comment]
Merge conflict above.  Also, I'm pretty sure this will not compile since #2325 was merged.

**Comment by mvandeberg** [comment]
Will look into it.

**Comment by mvandeberg** [comment]
@theoreticalbts Conflicts have been resolved.

**Comment by theoreticalbts** [comment]
It looks suspicious that the API call implementation parses code as `legacy_signed_transaction`, but the `cli_wallet` remote API declaration says `signed_transaction`.

Has `cli_wallet` transaction broadcast been tested?

Also, minor nitpick:  Signal field/method are named `on_applied_block`, `_on_applied_block_connection`.  But the signal refactoring standardized those names to `on_post_apply_block`, `_post_apply_block_conn`.

**Comment by mvandeberg** [comment]
I'll double check the wallet.

We need to document such naming conventions. I noticed that there was some renaming because of the changed signal names, but I guess I did not notice the standardization of the names. I can make the change.

**Comment by theoreticalbts** [comment]
Approved

**Pull request merged**
