### PR TITLE
Issue #1947 ( Follow/Tags Iterator Optimization )

### PR DESCRIPTION
**Pull request by mariusztrela**
Issue #1947

### CODE REVIEW

**Comment by mariusztrela** [comment]
It's hardly to separate all changes according to issues:
- #1947( Follow/Tags Iterator Optimization )
- #1948 ( Reuse Feed Objects )

My proposal is as follows:

- When issue #1947 will be closed, then issue #1948 should be closed too with flag: `duplicate`

**Comment by mvandeberg** [comment]
It doesn't need to be closed as a duplicate. You documented that separating the changes is difficult, as well as both issues the PR closes. When the PR is reviewed and merged, we'll close both issues.

**Comment by mvandeberg** [comment]
On my dev machine, this patch saved ~200M and reindexed 10 min faster than dev (running consensus + follow plugin). The memory usage should be accurate, but the timing (being a single run ) should not be taken as fact. This does indicate this patch saves space and likely does not hurt reindex time.

**Comment by mariusztrela** [comment]
https://docs.google.com/spreadsheets/d/19c9-CP5BkFQsMAnc-QX1d1TSupnMPYGLNu-8pKvU2IA/edit?ts=5a4e165b#gid=2011519849

**Comment by mariusztrela** [comment]
You should compare:
- branch `develop` commit: `6df95a8`  vs branch `std_allocator` commit: `9b26a59`
next
- branch `std_allocator` commit: `9b26a59` vs branch `std-allocator-follow-index2` commit: `dc280a8`

**Comment by mariusztrela** [comment]
branch `std-allocator-follow-index2` has the same implementation like in branch '1947-follow-tags-opt'

**Comment by mariusztrela** [comment]
This was tested for `follow-start-feeds = 0`

**Pull request merged**
