### PR TITLE
Reduce cost for all custom ops except follow custom ops

### PR DESCRIPTION
**Pull request by mvandeberg**

### CODE REVIEW

**Comment by nedsteem** [comment]
Zooming out for context of this issue, could we begin or point to the proposal for cost parameters set by Witnesses?

**Comment by theoreticalbts** [comment]
LGTM

**Comment by theoreticalbts** [comment]
@nedsteem This PR is basically tweaking a number.  Making it settable by the witnesses is something that's been proposed by the community (issue #2991 ), but it involves more code and dev time than this quick fix.

**Comment by bobinson** [comment]
@nedsteem It will be helpful to explain how we derived these values & their explanations IMHO.

1. custom_binary_operation_exec_time : what exactly is a custom binary ?
2. The comment says: `These numbers are obtained from computations in state_byte_hours.py script` but what exactly is script doing I feel should be explained to witnesses and they will explain to the end users/communities.

**Comment by Smittyvb** [comment]
Custom binary is like custom JSON, but for any binary blob.

**Comment by mvandeberg** [comment]
The state byte numbers are calculated from the python script.

The execution time numbers were derived from empirical testing. The previous custom json time was based on our full node (all plugins enabled) execution times, which includes significant execution times for custom ops used by the follow plugin. We want to account for those because they do incur significant costs to operating Steemit.com but we acknowledge that other Dapps make extensive use of custom ops and do not increase operating costs for Steemit.com at all. This change reduces the cost by 20x for all other custom ops, bring the cost in line with other lower impact operations.

**Comment by bobinson** [comment]
@mvandeberg So this is a way to find the time complexity ? Further by limiting the time certain actions/operations takes, are we trying to achieve Turing Completeness ?  

Doubt:
> The execution time numbers were derived from empirical testing. 

So these numbers are like acceptable values based on observation and may vary based on CPU types but we expect the max values to hold hood in majority of the scenarios. Is this how the values are decided ?

**Comment by Smittyvb** [comment]
@bobinson
> is a way to find the time complexity 

It determines how computationaly hard operations are.

> limiting the time

RCs don't limit how long nodes will process transactions. They just prevent a user from making too many operations that would overload nodes.

> Turing Completeness

What do you mean by this? C++ has been, and always has been turing complete. Steem users have never been able to run smart contracts.

**Comment by bobinson** [comment]
thank you @Smittyvb 

> Steem users have never been able to run smart contracts.


Ok, I was trying to understand as there was #308 and also https://github.com/steemit/steem/commit/abc27b3f4c3e740cfc7e1265bc298bfc47163f81

**Pull request merged**
