### PR TITLE
Instructions for re-compiling after hardfork

### PR DESCRIPTION
**Pull request by wmbutler**

### CODE REVIEW

**Comment by abitmore** [comment]
1. Should checkout special tag but not master branch. Sometimes master branch is not in sync (unfortunately).
2. Should add `-DCMAKE_BUILD_TYPE=Release` to `cmake` command by default

**Comment by abitmore** [comment]
`--rebuild-blockchain` should be `--replay-blockchain`?

**Comment by wmbutler** [comment]
I added the -DCMAKE_BUILD_TYPE but don't know what to do regarding the proper branch to check out.

**Comment by abitmore** [comment]
>I added the -DCMAKE_BUILD_TYPE but don't know what to do regarding the proper branch to check out.

I don't know either.

By the way I updated the original comment, please check.

**Comment by theoreticalbts** [comment]
Basically you want to put build instructions in the tree, which makes this a duplicate of #283.

**Pull request closed without merging**
