### PR TITLE
Issue 1330, eliminate object copies from loop iterations

### PR DESCRIPTION
**Pull request by vogel76**
Cleanup of 'auto' usage, especially during iteration over containers, where const reference shall be processed instead of object copy.

### CODE REVIEW

**Comment by vogel76** [comment]
I did a search under plugins/chain and only this one was matched (sorry I missed it previously). But in other part of code there are cases to be eliminated - shall I do it under this issue or leave as is ?

**Comment by mvandeberg** [comment]
Go ahead an eliminate this problem wherever it appears.

**Comment by mvandeberg** [comment]
Merge conflicts, please rebase or merge `develop`

**Comment by vogel76** [comment]
I have merged develop - I hope it is ready to merge back.

**Pull request merged**
