### PR TITLE
20160913 follow

### PR DESCRIPTION
**Pull request by mvandeberg**
Improvements to follow plugin, blogs, feeds, and database_api get_state. This is a non-consensus change but is needed for the next Steemit.com deployment.

### CODE REVIEW

**Comment by roadscape** [comment]
Does this new `get_discussions_by_blog ` replace `get_discussions_by_author_before_date`?

**Comment by mvandeberg** [comment]
I'm not quite sure what `get_discussions_by_author_before_date` is supposed to do, so yeah. Let's say it replaces it.

**Comment by roadscape** [comment]
`get_discussions_by_author_before_date` is the current method of paginating the Blog tab ;)

**Comment by mvandeberg** [comment]
Ok, so yes. It is the new way!

**Pull request merged**
